service: serverless-bert-lambda-docker

provider:
  name: aws # provider
  region: us-east-2 # aws region
  memorySize: 5120 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 6


functions:
  questionanswering:
    image: id.dkr.ecr.region.amazonaws.com/bert-lambda-docker@sha111:839c8bc0666666560d2ca7625127836dfb17a3831b2628a3c5cc52bbe842c701 #ecr url
    events:
      - http:
          path: qa # http path
          method: post # http method

